选项-显示新增显示扩展武将图片，设为默认开启
libccy/noname pull request #170
Opened 2023-07-23 01:58 UTC by lieren2023

选项-显示新增显示扩展武将图片，设为默认开启
#161

2023-07-23 13:47 UTC, xiaoas requested changes

2023-07-23 13:47 UTC, xiaoas commented on game/game.js
> +								if(Object.keys(lib.characterPack).some(pack => Object.keys(lib.characterPack[pack]).contains(name))){
`name in lib.characterPack[pack]`

2023-07-23 13:47 UTC, xiaoas commented on game/game.js
> +									var pack=Object.keys(lib.characterPack).find(pack => Object.keys(lib.characterPack[pack]).contains(name));
same as above

2023-07-23 13:47 UTC, xiaoas commented on game/game.js
> +								if(Object.keys(lib.characterPack).some(pack => Object.keys(lib.characterPack[pack]).contains(name))){
also this is a redundant `if` given the `var pack` statement below

2023-07-23 13:47 UTC, xiaoas commented on game/game.js
>  							else if(name.indexOf('::')!=-1){
the following name resolution fallbacks won't be reached if `lib.config.show_extensionimage` is set, which is incorrect behavior & render the config useless

2023-07-25 15:57 UTC, Spmario233 commented
虽然不知道有啥意义 不过还是合了算了

2023-07-25 15:57 UTC, merged