为扩展添加一个广泛用到的方法
libccy/noname pull request #2169
Opened 2024-12-30 23:27 UTC by dragonJadeRan

### PR受影响的平台

all
### 诱因和背景

来自和R喵8月份的谈话内容，最近看到R喵活了又想起来了😘
为扩展直接添加一个arenaReady方法
过去经常需要在content()/precontent()里手动添加，现在可以直接写了

### PR描述

为扩展直接添加一个arenaReady方法
过去经常需要在content()/precontent()里手动添加，现在可以直接写了

### PR测试

主要使用了多个用到了arenaReady时机的扩展进行测试（如十周年UI,千幻，炉石等等）

### 扩展适配

喵喵！不需要强制适配，但扩展作者可以迁移出在自己扩展里手动添加的该方法喵（如果有

### 检查清单

- [x] 我没有把该PR提交到`master`分支
- [x] commit中没有无用信息，和没有具体内容的“bugfix”
- [x] 我已经进行了充足的测试，且现有的测试都已通过
- [x] 如果此次PR中添加了新的武将，则我已在`character/rank.js`中添加对应的武将强度评级，并对双人武将/复姓武将添加`name:xxx`的参数
- [x] 如果此次PR中添加了新的语音文件，则我已在`lib.translate`中加入语音文件的文字台词
- [x] 如果此次PR涉及到新功能的添加，我已在`PR描述`中写入详细文档
- [x] 如果此次PR需要扩展跟进，我已在`扩展适配`中写入详细文档
- [x] 如果这个PR解决了一个issue，我在`诱因和背景`中明确链接到该issue
- [x] 我保证该PR中没有随意修改换行符等内容，没有制造出大量的Diff
- [x] 我保证该PR遵循项目中`.editorconfig`、`eslint.config.mjs`和`prettier.config.mjs`所规定的代码样式，并且已经通过`prettier`格式化过代码

2024-12-31 02:54 UTC, nonameShijian commented
可以，但只是简单的运用。有扩展需要多个ready.push的

2024-12-31 11:10 UTC, xizifu commented
onover是不是也可以加哦？

2025-01-01 02:58 UTC, dragonJadeRan commented
現在擴展可以正常用對象寫法寫武將了喵

2025-01-03 07:08 UTC, nonameShijian requested changes

2025-01-03 07:08 UTC, nonameShijian commented on noname/ui/create/menu/pages/exetensionMenu.js
> +							if (i =="arenaReady" || i == "content" || i == "precontent") {
判断多个改用Array.includes

2025-01-03 07:08 UTC, nonameShijian commented on noname/ui/create/menu/pages/exetensionMenu.js
> +							"function(){\n    \n}\n\n/*\n函数执行时机为舞台创建之后\n导出时本段代码中的换行、缩进以及注释将被清除\n*/";
为什么是舞台

2025-01-03 07:08 UTC, nonameShijian commented on noname/ui/create/menu/pages/exetensionMenu.js
> +					"function(){\n    \n}\n\n/*\n函数执行时机为游戏舞台创建之后\n导出时本段代码中的换行、缩进以及注释将被清除\n*/"
为什么是舞台

2025-01-03 07:08 UTC, nonameShijian commented on noname/init/loading.js
> +						// TODO 宝贝，有空看一下这里的原画和语音，绕得我头晕晕的。先睡一觉喵
todo

2025-01-03 07:08 UTC, nonameShijian commented on noname/init/loading.js
> +	function isClass(func) {//让我查查你是不是类喵
这个方法建议扔到utils里

2025-01-03 07:18 UTC, nonameShijian commented
以及需要使用示例

2025-01-04 00:16 UTC, dragonJadeRan commented
**extension.arenaReady示例**
过去牢扩展的代码：
在content/precontent中lib.arenaReady.push(function(){})
有时还可能要重复多个这样的步骤
一个函数会变得非常大，不利于模块化
现在可以直接在extension.arenaReady中写了。
# 如果你需要同时使用多个此时机，可以将function(){}改为class {
a(){}
b(){}
c(){}
}
导入时会自动将所有的方法推入lib.arenaReady。

**可以在extension.package.character.character中使用对象写法了**

2025-01-16 09:18 UTC, closed without merging