添加无懈ai
libccy/noname pull request #977
Opened 2024-02-21 14:39 UTC by hadeszoro

2024-02-21 15:06 UTC, Spmario233 commented
No 空格缩进
改成制表符缩进先

2024-02-22 10:06 UTC, universe-st reviewed
代码质量有较大提升空间。

2024-02-22 10:06 UTC, universe-st commented on card/guozhan.js
> +									if(!viewer.isMajor()) return 0;
对于多个条件，可以用&&（并符号）来合并结果。
这里可以：
if(get.mode()=='guozhan' && !_status._aozhan && !player.isMajor() && !viewer.isMajor())return 0;

2024-02-22 10:11 UTC, Spmario233 requested changes

2024-02-22 10:11 UTC, Spmario233 commented on card/guozhan.js
> +                    },
```suggestion
					order:function(item, player){
						if(!player) player=get.player();
						if(player.hasCard(function(card){
							return ['gz_haolingtianxia','gz_guguoanbang','gz_kefuzhongyuan','wuzhong','yuanjiao','lianjunshengyan','lulitongxin','yiyi'].includes(get.name(card));
						},'hs')) return 3.5;
						if(player.hasCard(function(card){
							return get.name(card)=='taoyuan';
						},'hs')) return get.order({name:'taoyuan'},player)-1;            
						return 9.5;
                    },
```

2024-02-22 10:13 UTC, Spmario233 approved these changes

2024-02-22 10:13 UTC, merged